site_name: Online Services Guides
site_url: https://guides.keresley.church
theme:
  name: readthedocs
  highlightjs: true
plugins:
- search
- mkdocstrings
- autorefs
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde